branch-defaults:
  default:
    environment: vaikhanasa-api-dev
    group_suffix: null
global:
  application_name: vaikhanasa-nidhi-backend
  branch: null
  default_ec2_keyname: vaikhanasa-eb-key
  default_platform: Node.js 24 running on 64bit Amazon Linux 2023
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
